# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GnhtDZq5c0rEQy3YgbHPyCQKKBblzHqM
"""

import streamlit as st
import pandas as pd
import pickle

# Load the model
with open('titanic_rf_xgb.pkl', 'rb') as f:
    model = pickle.load(f)

st.title("🚢 Titanic Survival Prediction App")

# Sidebar inputs
st.sidebar.header("Enter Passenger Details")

def user_input_features():
    Pclass = st.sidebar.number_input("Passenger Class (1, 2, 3)", min_value=1, max_value=3, value=3, step=1)
    Sex = st.sidebar.selectbox("Sex", ["male", "female"])
    Age = st.sidebar.number_input("Age", min_value=0, max_value=100, value=30, step=1)
    SibSp = st.sidebar.number_input("Siblings/Spouses Aboard", min_value=0, max_value=8, value=0, step=1)
    Parch = st.sidebar.number_input("Parents/Children Aboard", min_value=0, max_value=6, value=0, step=1)
    Fare = st.sidebar.number_input("Fare", min_value=0.0, max_value=600.0, value=50.0, step=1.0)
    Embarked = st.sidebar.selectbox("Port of Embarkation", ["C", "Q", "S"])

    # Prepare single row dataframe
    data = {
        'Pclass': Pclass,
        'Sex': Sex,
        'Age': Age,
        'SibSp': SibSp,
        'Parch': Parch,
        'Fare': Fare,
        'Embarked': Embarked
    }
    return pd.DataFrame([data])

input_df = user_input_features()
st.subheader("Passenger Data Entered:")
st.write(input_df)

# Apply the same encoding as used during training
input_df['Sex'] = input_df['Sex'].map({'male': 1, 'female': 0})
input_df['Embarked'] = input_df['Embarked'].map({'C': 0, 'Q': 1, 'S': 2})  # Must match training time encoding

# Make prediction
prediction = model.predict(input_df)[0]
prediction_proba = model.predict_proba(input_df)[0]

# Output prediction
st.subheader("Prediction:")
if prediction == 1:
    st.success(f"🎉 SURVIVED (Probability: {prediction_proba[1]:.2f})")
else:
    st.error(f"💀 NOT SURVIVED (Probability: {prediction_proba[0]:.2f})")